### ISSUE TITLE
MetaMask warning with `web3.eth.sign`

### ISSUE THREAD

**Issue by brandoncurtis** [0xProject/0x.js#162]
https://github.com/0xProject/0x.js/blob/4e22c289afcccdc46450f10bc15dfca8a6e2b151/src/web3_wrapper.ts#L92

`signTransactionAsync` uses `web3.eth.sign` instead of `web3.personal.sign`.

`web3.eth.sign` is deprecated and gives a scary warning in MetaMask:

> **Sign Message**
> Signing this message can have dangerous side effects. Only sign messages from sites you fully trust with your entire account. This dangerous method will be removed in a future version. [Read more here.][more]

from [read more here][more]:

> **Security Notice**
> These methods, personal_sign and its partner, personal_ecRecover have replaced the previous signature methods, eth_sign and eth_recover. That’s because the previous methods signed raw data unmodified, making it vulnerable to chosen ciphertext attacks, as well as potentially signing transactions you didn’t intend to. You can read more about the reasoning behind this change on [the go-ethereum repository][repo-geth].

Is there a reason not to replace e.g. 
```javascript
web3.eth.sign(web3.eth.defaultAccount,web3.toHex("msg"), (err,res) => console.log(err,res))
```
with this:
```javascript
web3.personal.sign(web3.toHex("msg"),web3.eth.defaultAccount, (err,res) => console.log(err,res))
```

Same result (I think), no error message.

[more]: https://medium.com/metamask/the-new-secure-way-to-sign-data-in-your-browser-6af9dd2a1527
[repo-geth]: https://github.com/ethereum/go-ethereum/pull/2940

**Comment by fabioberger** [comment]
Hi Brandon, 

Thanks for bringing this up. This is something we are aware of, but have decided not to change it to the `web3.personal.sign` implementation since it currently only supporting signing ASCII strings and would display as follows:

![](https://user-images.githubusercontent.com/6204356/30161571-685dca08-93d1-11e7-852f-d7e1ff4a920e.png)

This is hardly an improvement over the scary message where the user can at least see the actual orderHash they are signing.

We are drafting an EIP with a proposed solution that will solve this problem. Our solution follows that discussed in this comment: https://github.com/ethereum/EIPs/pull/683#issuecomment-328074258

We want a version of `web3.eth.sign` that will allow signers to display the actual data the user is signing the hash of so they can **actually** verify the specifics of what they are signing.

**Comment by fabioberger** [comment]
Our EIP has been received extremely well by the broader Ethereum ecosystem and we are working on getting it adopted by all major client nodes and signers. 

EIP: https://github.com/ethereum/EIPs/pull/712

**Comment by rawadrifai** [comment]
Metamask now hangs indefinitely when using web3.eth.sign.
Is this what's happening with 0x?

**Comment by miketeix** [comment]
Yeah same :(

**Comment by rawadrifai** [comment]
Found the solution for it! gotta use the web3.eth.sendAsync method. Metamask still doesn't support web3.eth.personal.sign. This is what we did for Taurus.io beta, which is relatively similar to 0x's concept except that it does derivatives, so contract HAVE to live on blockchain and executed later.

Web3 and Metamask just do not go well together :/

**Comment by fabioberger** [comment]
Hm, it's not hanging for me... Just tested this on Portal. Could you guys provide some repro steps?

**Comment by arisAlexis** [comment]
I wish this would be opened. signing in my dapp backend server with Metamask is the obvious way otherwise you need a username and password on top.

**Comment by fabioberger** [comment]
@arisAlexis do you have a repro you could share?

**Comment by arisAlexis** [comment]
actually eth.personal.sign works fine with Metamask, thanks
