### ISSUE TITLE
npm install 0x.js fails on clean node install

### ISSUE THREAD

**Issue by tomhschmidt** [0xProject/0x.js#310]
Just did a node install from their pkg download on a brand new machine. Running npm install fails, but
a) yarn works fine and
b) npm installing other packages works fine

```
node -v
v9.3.0

npm -v
5.6.0
```

```sudo npm install --save 0x.js
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/frozeman/bignumber.js-nolookahead.git /Users/tomhschmidt/.npm/_cacache/tmp/git-clone-58bc61de
npm ERR! /Users/tomhschmidt/.npm/_cacache/tmp/git-clone-58bc61de/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomhschmidt/.npm/_logs/2018-01-09T18_39_14_375Z-debug.log
macbook-pro:pipeline tomhschmidt$ sudo npm install --save 0x.js
Password:
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/frozeman/bignumber.js-nolookahead.git /Users/tomhschmidt/.npm/_cacache/tmp/git-clone-42a0a849
npm ERR! /Users/tomhschmidt/.npm/_cacache/tmp/git-clone-42a0a849/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomhschmidt/.npm/_logs/2018-01-09T19_30_18_792Z-debug.log
```

**Comment by citizens** [comment]
@tomhschmidt This is likely due to a web3.js dependency that is hosted on github rather than npm. Do you have git installed on you new machine? [This issue](https://github.com/frozeman/bignumber.js-nolookahead/issues/2) suggests that may be the problem. 

Otherwise there is an [open discussion](https://github.com/ethereum/web3.js/issues/904) in the web3.js repo. Apparently this dependency will go away in web3.js 1.0, but I'm unsure of a timeline.

**Comment by tomhschmidt** [comment]
@citizens Yup, have git installed
```
git --version
git version 2.14.3 (Apple Git-98)
```

I just tried installing web3 with npm and got the same error, so you're right. Kind of a bummer :/ -- weird that it works with yarn but not with npm

**Comment by fabioberger** [comment]
This is annoying. We have been waiting to upgrade to Web3 1.0 until it gets out of Beta but we might have to do so sooner :/
